branch-defaults:
  default:
    environment: null
    group_suffix: null
  dev_branch:
    environment: spring-boot-dev
deploy:
  artifact: target/tweets-api-0.0.1-SNAPSHOT.jar
global:
  application_name: spring-boot-tweets-api
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Corretto 17 running on 64bit Amazon Linux 2
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
